/*
 * DejaVu Sans outlines (src/font_data.h, generated by tools/gen_font.py).
 * Text is laid out with the font's advances and kerning pairs and drawn from
 * the same quadratic outlines in every backend.
 */
#include "canvas.h"

#include <stdint.h>
#include <string.h>

/* x2 is x * 2 plus the on-curve flag, so a point takes 4 bytes. */
typedef struct { short x2, y; } FontPoint;
/* Portable decoding: no shifts of negative values. */
#define PT_ON(p) ((p).x2 % 2 != 0)
#define PT_X(p) (((p).x2 - PT_ON(p)) / 2)
typedef struct { unsigned short codepoint, advance, point_start, point_count, contour_start, contour_count; } FontGlyph;
typedef struct { unsigned char a, b; short k; } FontKern;
typedef struct {
    int units_per_em, ascent, descent, glyph_count;
    const FontGlyph *glyphs;
    const FontPoint *points;
    const unsigned short *contour_ends;
    const FontKern *kern;
    int kern_count;
} FontFace;

#include "font_data.h"

static const FontFace *face(int bold) { return bold ? &font_bold : &font_regular; }

int font_units_per_em(int bold) { return face(bold)->units_per_em; }
int font_glyph_count(int bold) { return face(bold)->glyph_count; }

static int glyph_for(const FontFace *f, uint32_t cp) {
    if (cp >= 32 && cp < 127) return (int)cp - 32;
    if (cp == 0x2013 || cp == 0x2014) cp = '-';
    for (int i = 95; i < f->glyph_count; i++)
        if ((uint32_t)f->glyphs[i].codepoint == cp) return i;
    return '?' - 32;
}

static uint32_t next_codepoint(const char **text) {
    const unsigned char *s = (const unsigned char *)*text;
    if (s[0] < 0x80) {
        *text += 1;
        return s[0];
    }
    if ((s[0] & 0xe0) == 0xc0 && (s[1] & 0xc0) == 0x80) {
        *text += 2;
        return ((uint32_t)(s[0] & 0x1f) << 6) | (s[1] & 0x3f);
    }
    if ((s[0] & 0xf0) == 0xe0 && (s[1] & 0xc0) == 0x80 && (s[2] & 0xc0) == 0x80) {
        *text += 3;
        return ((uint32_t)(s[0] & 0x0f) << 12) | ((uint32_t)(s[1] & 0x3f) << 6) | (s[2] & 0x3f);
    }
    *text += 1;
    return '?';
}

/* Kerning for printable ASCII pairs, filled once by font_init before any thread starts. */
static short kern_table[2][95][95];

void font_init(void) {
    for (int bold = 0; bold < 2; bold++) {
        const FontFace *f = face(bold);
        memset(kern_table[bold], 0, sizeof(kern_table[bold]));
        for (int i = 0; i < f->kern_count; i++)
            if (f->kern[i].a >= 32 && f->kern[i].a < 127 && f->kern[i].b >= 32 && f->kern[i].b < 127)
                kern_table[bold][f->kern[i].a - 32][f->kern[i].b - 32] = f->kern[i].k;
    }
}

static int kerning(const FontFace *f, uint32_t a, uint32_t b) {
    if (a < 32 || a > 126 || b < 32 || b > 126) return 0;
    return kern_table[f == &font_bold][a - 32][b - 32];
}

size_t font_layout(const char *text, float size, int bold, PlacedGlyph *out, size_t max) {
    const FontFace *f = face(bold);
    float scale = size / (float)f->units_per_em, pen = 0;
    uint32_t previous = 0;
    size_t n = 0;
    while (*text) {
        uint32_t cp = next_codepoint(&text);
        int g = glyph_for(f, cp);
        if (previous) pen += (float)kerning(f, previous, cp) * scale;
        if (n < max) {
            out[n].glyph = g;
            out[n].x = pen;
        }
        n++;
        pen += (float)f->glyphs[g].advance * scale;
        previous = cp;
    }
    return n < max ? n : max;
}

float font_width(const char *text, float size, int bold) {
    const FontFace *f = face(bold);
    float scale = size / (float)f->units_per_em, pen = 0;
    uint32_t previous = 0;
    while (*text) {
        uint32_t cp = next_codepoint(&text);
        if (previous) pen += (float)kerning(f, previous, cp) * scale;
        pen += (float)f->glyphs[glyph_for(f, cp)].advance * scale;
        previous = cp;
    }
    return pen;
}

/* DejaVu Sans capitals are 1493 of 2048 units tall in both weights. */
float font_cap_height(float size, int bold) {
    (void)bold;
    return size * 0.729f;
}
float font_descender(float size, int bold) { return size * (float)(-face(bold)->descent) / (float)face(bold)->units_per_em; }

void font_outline(int bold, int glyph, const OutlineSink *sink, void *ctx) {
    const FontFace *f = face(bold);
    const FontGlyph *g = &f->glyphs[glyph];
    const FontPoint *pts = f->points + g->point_start;
    int start = 0;
    for (int c = 0; c < g->contour_count; c++) {
        int end = f->contour_ends[g->contour_start + c];
        int n = end - start;
        if (n < 2) {
            start = end;
            continue;
        }
        /* Start on an on-curve point; if none, start at the midpoint of the first two off-curve points. */
        int first_on = -1;
        for (int i = 0; i < n; i++)
            if (PT_ON(pts[start + i])) {
                first_on = i;
                break;
            }
        float sx, sy;
        int k0;
        if (first_on >= 0) {
            sx = PT_X(pts[start + first_on]);
            sy = pts[start + first_on].y;
            k0 = first_on;
        } else {
            sx = (float)(PT_X(pts[start]) + PT_X(pts[start + 1])) / 2.0f;
            sy = (pts[start].y + pts[start + 1].y) / 2.0f;
            k0 = 0;
        }
        sink->move(ctx, sx, sy);
        int have_control = 0;
        float cx = 0, cy = 0;
        for (int step = 1; step <= n; step++) {
            const FontPoint *p = &pts[start + (k0 + step) % n];
            float px = (float)PT_X(*p), py = p->y;
            if (PT_ON(*p)) {
                if (have_control) sink->quad(ctx, cx, cy, px, py);
                else sink->line(ctx, px, py);
                have_control = 0;
            } else {
                if (have_control) {
                    float mx = (cx + px) / 2, my = (cy + py) / 2;
                    sink->quad(ctx, cx, cy, mx, my);
                }
                cx = px;
                cy = py;
                have_control = 1;
            }
        }
        if (have_control) sink->quad(ctx, cx, cy, sx, sy);
        sink->close(ctx);
        start = end;
    }
}
